### ISSUE TITLE
Support for ARMv7

### ISSUE THREAD

**Issue by JackSabbath** [Chasing66/peer2profit#31]
Your introduction says "Support Docker image for linux/386, linux/amd64, linux/arm/v7, linux/arm64".

However, when I try to this on my Raspberry, I get the error message

```
me@ubuntu:~# docker-compose up
[+] Running 0/1
 ⠇ Peer2Profit Pulling                                                                        1.8s
no matching manifest for linux/arm/v7 in the manifest list entries
```

The entry on my docker-compose.yaml looks like this:

```
    Peer2Profit:
        container_name: Peer2Profit
        image: enwaiax/peer2profit:alpine
        environment:
            - email= ...
            - use_proxy=false
        restart: unless-stopped
```

Am I doing something wrong or is amd64 actually the only supported arch? I also tried the `latest` for the debian image, but that yielded the same error.
